import { ArrowRight, Check, FileText, Heart, Plus, Sparkles } from 'lucide-react'
import PageHeader from '../../components/PageHeader.jsx'
import { dateLabel, money } from '../../utils/format.js'

export default function DashboardPage({ organisation, receipts, onNavigate, onPreview }) {
  return <>
    <PageHeader eyebrow="YOUR WORKSPACE" title={<>Good morning, Admin <span className="wave">✳</span></>} description="Here is a clear view of the contributions you have recorded." action={<button className="primary" onClick={() => onNavigate('new')}><Plus size={19} /> Create receipt</button>} />
    <div className="hero-banner"><div className="hero-copy"><div className="hero-kicker"><Sparkles size={15} /> A little good goes a long way</div><h2>Make gratitude part of every gift.</h2><p>Create a beautiful receipt in just a few steps and keep every donation accounted for.</p><button onClick={() => onNavigate('new')}>Create your first receipt <ArrowRight size={17} /></button></div><div className="hero-graphic"><div className="graphic-circle one" /><div className="graphic-circle two" /><div className="graphic-paper"><div className="graphic-logo"><Heart size={16} fill="currentColor" /></div><div className="graphic-line wide" /><div className="graphic-line" /><div className="graphic-total">₹ 10,000 <Check size={17} /></div><div className="graphic-line short" /></div></div></div>
    <div className="stats"><div className="stat"><span>Total receipts</span><strong>{String(receipts.length).padStart(2, '0')}</strong><small>Saved receipts</small></div><div className="stat"><span>Donations recorded</span><strong>{money(receipts.reduce((sum, receipt) => sum + Number(receipt.amount), 0))}</strong><small>Across all receipts</small></div><div className="stat"><span>Your organisation</span><strong className="org-status">{organisation.name ? 'Ready to go' : 'Setup needed'}</strong><small>{organisation.name ? 'Details completed' : 'Add details to begin'}</small></div></div>
    <div className="section-heading"><div><h3>Recent receipts</h3><p>Your latest donation records appear here.</p></div><button className="text-button" onClick={() => onNavigate('receipts')}>View all <ArrowRight size={16} /></button></div>
    {receipts.length ? <div className="record-list">{receipts.slice(0, 4).map(receipt => <button key={receipt.receiptNo} className="record-row" onClick={() => onPreview(receipt)}><span className="record-avatar">{receipt.donorName[0]}</span><span><strong>{receipt.donorName}</strong><small>{receipt.receiptNo} · {dateLabel(receipt.date)}</small></span><b>{money(receipt.amount)}</b><ArrowRight size={17} /></button>)}</div> : <div className="empty"><div className="empty-icon"><FileText size={26} /></div><strong>No receipts yet</strong><p>Your first receipt is just a few clicks away.</p><button onClick={() => onNavigate('new')}>Create a receipt <ArrowRight size={16} /></button></div>}
  </>
}
